export const SAMPLE_IMAGES = [
  {
    id: 'cinematic',
    url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1920&h=1080&fit=crop&crop=center',
    label: 'Cinematic',
  },
  {
    id: 'nature',
    url: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1920&h=1080&fit=crop&crop=center',
    label: 'Nature',
  },
  {
    id: 'city',
    url: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1920&h=1080&fit=crop&crop=center',
    label: 'City',
  },
];

export const DEVICES = [
  // ── CTV ──────────────────────────────────────────────────────────────────
  {
    id: 'apple-tv',
    displayName: 'Apple TV',
    platform: 'tvOS',
    category: 'ctv',
    viewport: { width: 1920, height: 1080 },
    inputModel: 'dpad',
    safeAreaInset: { top: 60, right: 96, bottom: 60, left: 96 },
    uiScale: 1.6,
    bezelType: 'tv',
    renderNotes: "tvOS Focus Engine auto-highlights and slightly scales focused elements (~10% enlarge). D-pad only — no cursor or touch. Action-safe margins (~5%) prevent edge clipping on older displays. Requires large text and generous touch targets for 10-foot viewing.",
    revenueNote: "Missing focus ring → ~4% of Siri Remote users can't locate the subscribe button → est. $200 lost / 1k impressions",
    breakItBug: {
      type: 'missing-focus',
      label: 'Focus ring missing — nothing shows what\'s selected',
      description: 'A custom :focus style overrides the tvOS system ring but the new style never fires. The user navigates blind — common when CSS focus-visible is wrongly suppressed.',
    },
  },
  {
    id: 'roku',
    displayName: 'Roku',
    platform: 'BrightScript / SceneGraph',
    category: 'ctv',
    viewport: { width: 1920, height: 1080 },
    inputModel: 'dpad',
    safeAreaInset: { top: 60, right: 96, bottom: 60, left: 96 },
    uiScale: 1.6,
    bezelType: 'tv',
    renderNotes: "Roku is NOT a web renderer. SceneGraph draws UI with BrightScript primitives — no CSS, no web fonts, no DOM. Images must be pre-sized; the platform enforces a hard ~40 MB image memory budget per channel.",
    revenueNote: "Hero image exceeds memory budget → background renders blank → trust broken before CTA loads → est. $300 lost / 1k impressions",
    breakItBug: {
      type: 'image-fail',
      label: 'Hero image exceeds the ~40 MB Roku memory budget',
      description: 'Roku channels frequently hit memory limits with full-bleed hero images. The image fails silently — users see a broken placeholder where the background should be.',
    },
  },
  {
    id: 'fire-tv',
    displayName: 'Fire TV',
    platform: 'Android Leanback',
    category: 'ctv',
    viewport: { width: 1920, height: 1080 },
    inputModel: 'dpad',
    safeAreaInset: { top: 54, right: 96, bottom: 54, left: 96 },
    uiScale: 1.6,
    bezelType: 'tv',
    renderNotes: "Android Leanback requires explicit nextFocusDown / nextFocusUp chains on each focusable View. Broken focus order is the #1 CTV paywall bug — if the user's remote can't reach the buy button, the conversion never happens.",
    revenueNote: "Focus trap on 'Restore Purchase' → D-pad can never reach 'Start Free Trial' → est. $800 lost / 1k impressions",
    breakItBug: {
      type: 'focus-trap',
      label: 'Focus trapped — D-pad cannot reach the purchase button',
      description: 'An incorrect nextFocusDown assignment traps focus on the secondary action. "Start Free Trial" is rendered in the DOM but unreachable from the remote.',
    },
  },
  {
    id: 'google-tv',
    displayName: 'Google TV',
    platform: 'Android TV / Leanback',
    category: 'ctv',
    viewport: { width: 1920, height: 1080 },
    inputModel: 'dpad',
    safeAreaInset: { top: 54, right: 96, bottom: 54, left: 96 },
    uiScale: 1.6,
    bezelType: 'tv',
    renderNotes: "Google TV runs Android Leanback with the same D-pad focus model as Fire TV. Leanback's DefaultFocusHighlight is the default ring, but custom styling requires disabling it and implementing focus state in the View layer.",
    revenueNote: "Font hardcoded in px instead of sp → text renders at 2–3 physical pixels on 4K → price illegible → est. $150 lost / 1k impressions",
    breakItBug: {
      type: 'tiny-font',
      label: 'Font in px, not sp — price and headline render at 2px on 4K',
      description: 'Android Leanback TextViews expect sp (scale-independent pixels). Hardcoded px values ignore the device\'s font-scale setting and 4K upscaling — a 14sp headline renders as ~2 physical pixels on a 4K panel.',
    },
  },
  {
    id: 'samsung',
    displayName: 'Samsung',
    platform: 'Tizen (Chromium-based)',
    category: 'ctv',
    viewport: { width: 1920, height: 1080 },
    inputModel: 'dpad',
    safeAreaInset: { top: 54, right: 96, bottom: 54, left: 96 },
    uiScale: 1.6,
    bezelType: 'tv',
    renderNotes: "Tizen uses a Chromium-derived web renderer, so CSS mostly works — but the GPU budget is limited. Complex gradients, shadows, and backdrop-filter can drop frame rate below 30 fps on 2018–2020 models.",
    revenueNote: "overflow:hidden clips focus ring on card edges → D-pad users navigate blind near boundaries → est. $180 lost / 1k impressions",
    breakItBug: {
      type: 'overflow-clip',
      label: 'overflow:hidden on card — focus ring clipped at container edges',
      description: 'Tizen\'s compositing clips CSS outlines when overflow:hidden is set on a parent — unlike Chrome. A focused button at the card edge has its ring visually cut off, leaving D-pad users disoriented about what\'s selected.',
    },
  },
  {
    id: 'lg',
    displayName: 'LG',
    platform: 'webOS (Chromium-based)',
    category: 'ctv',
    viewport: { width: 1920, height: 1080 },
    inputModel: 'dpad',
    safeAreaInset: { top: 54, right: 96, bottom: 54, left: 96 },
    uiScale: 1.6,
    bezelType: 'tv',
    renderNotes: "webOS is also Chromium-based with spatial navigation (SDKM). LG's Magic Remote adds pointer support on newer models, but paywall flows must be D-pad-first. Font rendering differs slightly from desktop Chromium.",
    revenueNote: "Missing :focus-visible → pointer users (Magic Remote) look fine in QA, D-pad users navigate blind → est. $200 lost / 1k impressions",
    breakItBug: {
      type: 'no-focus-visible',
      label: ':focus-visible missing — D-pad navigation invisible while pointer looks fine',
      description: 'LG Magic Remote can switch between pointer and D-pad modes. Without :focus-visible styles, pointer users see hover states and appear fine in QA — but D-pad-only users get zero visual feedback navigating the paywall.',
    },
  },
  {
    id: 'vizio',
    displayName: 'Vizio',
    platform: 'SmartCast (Chromium-based)',
    category: 'ctv',
    viewport: { width: 1920, height: 1080 },
    inputModel: 'dpad',
    safeAreaInset: { top: 80, right: 128, bottom: 80, left: 128 },
    uiScale: 1.6,
    bezelType: 'tv',
    renderNotes: "SmartCast runs a Chromium renderer but has an aggressive overscan boundary (~7%) — larger than most competitors. Low GPU budget means animations should be minimal. Safe-area violations are the top Vizio paywall complaint.",
    revenueNote: "CTA in overscan dead zone → button clipped by bezel on ~8% of older Vizio panels → est. $300 lost / 1k impressions",
    breakItBug: {
      type: 'safe-area-overflow',
      label: 'CTA outside the action-safe zone — invisible on real hardware',
      description: 'The purchase button renders past the action-safe boundary. On real Vizio hardware, overscan clips this region — the button exists in the DOM but is invisible and unreachable.',
    },
  },
  {
    id: 'xbox',
    displayName: 'Xbox',
    platform: 'Microsoft Edge (Chromium)',
    category: 'ctv',
    viewport: { width: 1920, height: 1080 },
    inputModel: 'dpad',
    safeAreaInset: { top: 54, right: 96, bottom: 54, left: 96 },
    uiScale: 1.6,
    bezelType: 'tv',
    renderNotes: "Xbox uses an Edge-based Chromium renderer in its app container. Gamepad navigation follows D-pad spatial focus. The Xbox System UI overlays status elements at screen edges, requiring safe-area respect even on this modern platform.",
    revenueNote: "No tabindex → gamepad D-pad finds zero focusable elements, controller frozen on paywall → est. $600 lost / 1k impressions",
    breakItBug: {
      type: 'no-tabindex',
      label: 'tabindex missing — gamepad D-pad cannot reach any button',
      description: 'Xbox Edge relies on tabindex to build the spatial-navigation graph. Without it, the controller D-pad finds no focusable elements — the gamepad appears frozen. Users who can\'t subscribe with a controller rarely switch to a phone to complete the flow.',
    },
  },
  // ── MOBILE ───────────────────────────────────────────────────────────────
  {
    id: 'ios',
    displayName: 'iOS',
    platform: 'Safari / WKWebView',
    category: 'mobile',
    viewport: { width: 390, height: 844 },
    inputModel: 'touch',
    safeAreaInset: { top: 59, right: 0, bottom: 34, left: 0 },
    uiScale: 1.0,
    bezelType: 'phone-ios',
    renderNotes: "iOS safe areas: ~59px top (Dynamic Island + status bar) and 34px bottom (home indicator). The CSS API is env(safe-area-inset-*). Missing bottom padding is the #1 iOS subscription-app bug — the purchase button hides behind the home indicator.",
    revenueNote: "CTA behind home indicator → tap triggers swipe-up gesture instead of purchase → est. $350 lost / 1k impressions (~7% iOS abort rate)",
    breakItBug: {
      type: 'safe-area-hidden',
      label: 'CTA hidden behind the home indicator — untappable',
      description: 'Omitting padding-bottom: env(safe-area-inset-bottom) pushes the button under the home indicator swipe area. It renders but the touch target is blocked by the system UI.',
    },
  },
  {
    id: 'android',
    displayName: 'Android',
    platform: 'Chrome / WebView',
    category: 'mobile',
    viewport: { width: 393, height: 873 },
    inputModel: 'touch',
    safeAreaInset: { top: 32, right: 0, bottom: 48, left: 0 },
    uiScale: 1.0,
    bezelType: 'phone-android',
    renderNotes: "Android safe areas vary by OEM and gesture mode (3-button vs. swipe). The bottom inset ranges from 0–48px. Use WindowInsetsCompat or CSS env() to handle this. Back-gesture conflicts with paywall dismiss are a common Android UX bug.",
    revenueNote: "CTA behind gesture nav bar → tap triggers back gesture, exits paywall → est. $450 lost / 1k impressions (~9% Android abort rate)",
    breakItBug: {
      type: 'android-safe-area',
      label: 'WindowInsets not applied — CTA behind gesture navigation bar',
      description: 'Android gesture navigation insets range from 0–48px depending on OEM and mode. Without consuming WindowInsetsCompat, the CTA overlaps the navigation bar — tapping the lower half triggers the system back gesture and exits the purchase flow.',
    },
  },
  // ── WEB ──────────────────────────────────────────────────────────────────
  {
    id: 'chrome',
    displayName: 'Chrome',
    platform: 'Chromium',
    category: 'web',
    viewport: { width: 1280, height: 768 },
    inputModel: 'cursor',
    safeAreaInset: { top: 0, right: 0, bottom: 0, left: 0 },
    uiScale: 1.0,
    bezelType: 'browser-chrome',
    renderNotes: "Chrome is the de-facto web standard and your baseline. Flexbox, grid, backdrop-filter, CSS variables, and web animations all behave as specified. Test here first, then verify divergence on Safari and Edge.",
    revenueNote: "Cookie consent banner renders above paywall on first visit → offer blocked before user sees price → est. $120 lost / 1k impressions",
    breakItBug: {
      type: 'cookie-banner',
      label: 'Cookie consent banner z-index > paywall — offer blocked on first visit',
      description: 'The consent SDK injects a fixed banner at z-index: 9999. Your paywall renders at z-index: 1. First-time Chrome visitors see the cookie prompt before — or instead of — the paywall. ~12% abandon the flow without ever seeing the price.',
    },
  },
  {
    id: 'safari',
    displayName: 'Safari',
    platform: 'WebKit',
    category: 'web',
    viewport: { width: 1280, height: 768 },
    inputModel: 'cursor',
    safeAreaInset: { top: 0, right: 0, bottom: 0, left: 0 },
    uiScale: 1.0,
    bezelType: 'browser-safari',
    renderNotes: "Safari / WebKit still diverges from Chromium: backdrop-filter needed a -webkit- prefix until Safari 15.4, flexbox gap was missing until Safari 14.1, and position: sticky inside overflow: hidden silently breaks. Test Safari separately.",
    revenueNote: "backdrop-filter renders as solid black on Safari 13–14 → card looks broken → est. $80 lost / 1k impressions (visual trust break)",
    breakItBug: {
      type: 'css-quirk',
      label: 'backdrop-filter not rendering — card loses frosted-glass effect',
      description: 'Older Safari omits backdrop-filter without the -webkit- prefix. The card falls back to a solid background — the background image stops showing through and visual depth collapses.',
    },
  },
  {
    id: 'edge',
    displayName: 'Edge',
    platform: 'Chromium (EdgeHTML legacy note)',
    category: 'web',
    viewport: { width: 1280, height: 768 },
    inputModel: 'cursor',
    safeAreaInset: { top: 0, right: 0, bottom: 0, left: 0 },
    uiScale: 1.0,
    bezelType: 'browser-edge',
    renderNotes: "Modern Edge is Chromium-based and behaves nearly identically to Chrome for rendering. The main paywall risk is enterprise managed-browser policies: cookie restrictions, pop-up blockers, and Content Security Policy overrides that silently break payment flows.",
    revenueNote: "Enterprise CSP strips inline styles → paywall renders blank for ~15% of corporate users → est. $200 lost / 1k impressions",
    breakItBug: {
      type: 'csp-blocked',
      label: 'Enterprise CSP blocks inline styles — paywall renders blank',
      description: 'Managed Edge deployments enforce strict Content-Security-Policy headers that block inline style attributes. All visual styling is stripped — users see a blank or barely-visible paywall. Affects ~15% of corporate subscribers who browse on managed devices.',
    },
  },
];

export const DEVICES_BY_CATEGORY = {
  ctv: DEVICES.filter(d => d.category === 'ctv'),
  mobile: DEVICES.filter(d => d.category === 'mobile'),
  web: DEVICES.filter(d => d.category === 'web'),
};

export const getDevice = id => DEVICES.find(d => d.id === id);
